package exceptions;

import java.util.ArrayList;
import java.util.List;

public class Test {

	public static void main(String[] args) {
		Division d = new Division(3, 0);
		//try {
			System.out.println("div"+d.div());
//		}catch(ArithmeticException e) {
//			System.out.println(e);
//		}
//			List <Test> test =new ArrayList<>();
//			test.iterator().hasNext();
	}
}
